"""
readme_generator.py
-------------------
Generates a plain text README.txt file from the structured metadata
produced by the FAIRifyer pipeline.

Follows the EPFL Library README standard:
  Varrato, Borel, Gabella (2022). "README file for datasets:
  Best practices and template." EPFL.
  https://infoscience.epfl.ch/record/298249

Standard sections:
  1. General Information
  2. Dataset Identifier & Access Information
  3. File Overview & Structure
  4. Data Collection (Acquisition Parameters)
  5. Data Processing (Reconstruction Parameters)
  6. Data Dictionary (variables, units, abbreviations)
  7. FAIR Compliance & Completeness

Public API
----------
    from fairify.readme_generator import generate_readme

    generate_readme(structured, output_path="README.txt")
"""

from datetime import datetime
from pathlib import Path
from typing import Any, Dict, Optional


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _clean(value: Any, fallback: str = "[Not specified]") -> str:
    """Strip surrounding quotes that vendor software sometimes adds."""
    if value is None:
        return fallback
    s = str(value).strip().strip('"').strip("'").strip()
    return s if s and s not in ('""',"''") else fallback


def _quantity_str(q: Any, fallback: str = "[Not found]") -> str:
    """Format a {"value": ..., "unit": ...} quantity as a readable string."""
    if q is None:
        return fallback
    if isinstance(q, dict):
        v = q.get("value")
        u = q.get("unit", "")
        if v is None:
            return fallback
        return f"{v} {u}".strip()
    return _clean(q, fallback)


def _sep(char: str = "-", width: int = 60) -> str:
    return char * width


def _completeness_bar(percent: float, width: int = 30) -> str:
    filled = int(round(percent / 100 * width))
    bar = "#" * filled + "-" * (width - filled)
    return f"[{bar}] {percent:.1f}%"


# ---------------------------------------------------------------------------
# Section builders  (plain text, EPFL standard)
# ---------------------------------------------------------------------------

def _build_title(ext: Dict, generated_at: str) -> str:
    sample  = _clean(ext.get("sample_id"),      "CT Imaging Dataset")
    project = _clean(ext.get("project_name"),   "EXCITE2")
    date    = generated_at[:10]
    return f"""{_sep("=")}
README — {sample}
{_sep("=")}
Generated by FAIRifyer (EXCITE2 FAIRification pipeline)
Date generated : {date}
Standard       : EPFL Library README Best Practices (Varrato et al., 2022)
"""


def _build_general(ext: Dict, dataset_path: str, generated_at: str) -> str:
    sample   = _clean(ext.get("sample_id"),            "Not specified")
    project  = _clean(ext.get("project_name"),         "EXCITE2")
    domain   = _clean(ext.get("application_domain"),   "Not specified")
    owner    = _clean(ext.get("data_owner"),            "Not specified")
    contact  = _clean(ext.get("contact_person"),        "Not specified")
    operator = _clean(ext.get("operator_name"),         "Not specified")
    scan_id  = _clean(ext.get("scan_identifier"),       "Not specified")
    start    = _clean(ext.get("acquisition_start_time"),"Not specified")
    end      = _clean(ext.get("acquisition_end_time"),  "Not specified")
    notes    = _clean(ext.get("notes"),                 "None")

    return f"""
{_sep()}
1. GENERAL INFORMATION
{_sep()}

Title              : {sample}
Project            : {project}
Application domain : {domain}
Scan identifier    : {scan_id}

Author / Data owner : {owner}
Contact person      : {contact}
Operator            : {operator}

Date of acquisition (start) : {start}
Date of acquisition (end)   : {end}

Dataset location   : {dataset_path}
Notes              : {notes}
"""


def _build_access(ext: Dict, generated_at: str) -> str:
    owner  = _clean(ext.get("data_owner"), "Author")
    sample = _clean(ext.get("sample_id"),  "CT Dataset")
    year   = generated_at[:4]
    project = _clean(ext.get("project_name"), "EXCITE2")

    return f"""
{_sep()}
2. DATASET IDENTIFIER & ACCESS INFORMATION
{_sep()}

Persistent identifier (DOI) : [Add DOI after repository deposit]
Repository                  : 4TU.ResearchData / Zenodo
License                     : [Specify license, e.g. CC BY 4.0]
Access conditions           : [Open / Restricted / Embargoed]

Recommended citation:
  {owner} ({year}). {sample} [Dataset].
  {project}. 4TU.ResearchData.
  https://doi.org/[ADD DOI HERE]

Terms of use:
  - Please cite this dataset when using it in publications.
  - Contact the data owner for questions about reuse.
"""


def _build_file_overview(dataset_path: str) -> str:
    return f"""
{_sep()}
3. FILE OVERVIEW & STRUCTURE
{_sep()}

Dataset root folder:
  {dataset_path}

File structure:
  README.txt                   This file
  metadata_excite.json         Machine-readable FAIR metadata (EXCITE2 schema)
  *.xml / *.txt / *.log        Vendor acquisition log files (metadata source)
  *.txrm / *.txm               Raw projection data (vendor format)
  *.vol / *.tif                Reconstructed volume files (if present)
  reconstructed/               Subfolder for reconstructed data (if present)

File formats:
  - .json    : JavaScript Object Notation, open standard, machine-readable
  - .xml     : eXtensible Markup Language, vendor metadata format
  - .txrm    : ZEISS/Carl Zeiss X-ray microscopy raw data format
  - .vol     : Binary volume data format
  - .txt     : Plain text, human-readable

Naming convention:
  Dataset folders follow the pattern:
  [voxelsize]um_[voltage]kV_[power]W_[exposure]ms_[averages]av_[filter]
  Example: 23um_140kV_23W_75ms_5av_1mmAl

File encoding : UTF-8
Date format   : ISO 8601 (YYYY-MM-DDThh:mm:ssZ)
"""


def _build_acquisition(ext: Dict, conceptual: Dict) -> str:
    instr  = _clean(ext.get("instrument_name"),          "Not specified")
    model  = _clean(ext.get("instrument_model"),         "Not specified")
    serial = _clean(ext.get("instrument_serial_number"), "Not specified")
    sw     = _clean(ext.get("software_version"),         "Not specified")
    tube   = _clean(ext.get("xray_tube_name"),           "Not specified")
    diam   = _clean(ext.get("sample_diameter_mm"),       "Not specified")

    geo  = conceptual.get("sample_positioning") or {}
    sod  = _quantity_str(geo.get("source_object_distance"),   "[Not found]")
    odd  = _quantity_str(geo.get("object_detector_distance"), "[Not found]")
    sdd  = _quantity_str(geo.get("source_detector_distance"), "[Not found]")
    mag  = _quantity_str(conceptual.get("optical_magnification"), "[Not found]")
    kv   = _quantity_str(conceptual.get("energy"),            "[Not found]")
    pw   = _quantity_str(conceptual.get("power"),             "[Not found]")
    ua   = _quantity_str(conceptual.get("current"),           "[Not found]")
    filt = _clean(conceptual.get("aperture_filter"),          "Not specified")
    exp  = _quantity_str(conceptual.get("exposure_time"),     "[Not found]")
    proj = _quantity_str(conceptual.get("total_num_projections"), "[Not found]")
    time = _quantity_str(conceptual.get("total_scan_time"),   "[Not found]")
    vox  = _quantity_str(conceptual.get("voxel_size"),        "[Not found]")
    mode = _clean(conceptual.get("scanning_mode"),            "Not specified")

    img  = conceptual.get("image_size") or {}
    iw   = _quantity_str(img.get("width"),  "[Not found]")
    ih   = _quantity_str(img.get("height"), "[Not found]")

    return f"""
{_sep()}
4. DATA COLLECTION — ACQUISITION PARAMETERS
{_sep()}

Instrument
  - Name           : {instr}
  - Model          : {model}
  - Serial number  : {serial}
  - Software       : {sw}
  - X-ray tube     : {tube}
  - Sample diameter: {diam} mm

Geometry (sample positioning)
  - Source-Object Distance (SOD)    : {sod}
  - Object-Detector Distance (ODD)  : {odd}
  - Source-Detector Distance (SDD)  : {sdd}
  - Optical magnification           : {mag}

X-ray source settings
  - Tube voltage (energy)  : {kv}
  - Tube power             : {pw}
  - Tube current           : {ua}
  - Aperture filter        : {filt}

Scanning settings
  - Exposure time per projection : {exp}
  - Total number of projections  : {proj}
  - Total scan time              : {time}
  - Scanning mode                : {mode}

Detector / image
  - Voxel / pixel size : {vox}
  - Image width        : {iw}
  - Image height       : {ih}
"""


def _build_reconstruction(conceptual: Dict) -> str:
    rec  = conceptual.get("reconstruction") or {}
    algo = _clean(rec.get("algorithm"),                "[Not specified]")
    filt = _clean(rec.get("filter"),                   "[Not specified]")
    cs   = _quantity_str(rec.get("center_shift"),      "[Not specified]")
    bhc  = _clean(rec.get("beam_hardening_algorithm"), "[Not specified]")
    rot  = _quantity_str(rec.get("rotation_angle"),    "[Not specified]")
    grey = _clean(rec.get("grey_level"),               "[Not specified]")

    return f"""
{_sep()}
5. DATA PROCESSING — RECONSTRUCTION PARAMETERS
{_sep()}

  - Algorithm                    : {algo}
  - Filter                       : {filt}
  - Centre-of-rotation shift     : {cs}
  - Beam hardening correction    : {bhc}
  - Rotation angle               : {rot}
  - Grey level scaling           : {grey}
"""


def _build_dictionary() -> str:
    return f"""
{_sep()}
6. DATA DICTIONARY — ABBREVIATIONS & UNITS
{_sep()}

Parameter abbreviations:
  SOD   Source-Object Distance      (distance from X-ray source to sample)
  ODD   Object-Detector Distance    (distance from sample to detector)
  SDD   Source-Detector Distance    (total source-to-detector distance)
  BHC   Beam Hardening Correction

Units used in this dataset:
  mm    millimetre
  um    micrometre (micrometres, 1 um = 0.001 mm)
  kV    kilovolt   (tube voltage)
  W     watt       (tube power)
  uA    microampere (tube current)
  s     second     (time)
  px    pixel      (image dimensions, centre shift)
  deg   degree     (rotation angle)
  x     magnification factor (dimensionless)

Date/time format : ISO 8601 — YYYY-MM-DDThh:mm:ssZ (UTC)
"""


def _build_fair(validation: Dict, missing_fields: list) -> str:
    pct     = validation.get("completeness_percent", 0.0)
    bar     = _completeness_bar(pct)
    missing = validation.get("summary", {}).get("required_missing", missing_fields)
    passed  = "PASS" if validation.get("overall_pass") else "FAIL"
    issues  = validation.get("summary", {}).get("total_issues", 0)

    missing_lines = "\n".join(f"  - {f}" for f in missing) if missing else "  - None (all required fields present)"

    return f"""
{_sep()}
7. FAIR COMPLIANCE & COMPLETENESS
{_sep()}

Validation result  : {passed}
Completeness score : {bar}
Total issues found : {issues}

Missing required fields:
{missing_lines}

FAIR principles compliance:
  - Findable     : Persistent identifier (DOI) — add after deposit
  - Accessible   : Open access via 4TU.ResearchData / Zenodo
  - Interoperable: EXCITE2 metadata schema, JSON-LD with schema.org context
  - Reusable     : License specified above, provenance documented

{_sep("=")}
END OF README
{_sep("=")}
"""


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def generate_readme(
    structured: Dict[str, Any],
    output_path: Optional[str] = None,
) -> str:
    """
    Generate a plain text README.txt following the EPFL Library standard
    (Varrato, Borel, Gabella 2022) from a FAIRifyer structured metadata record.

    Parameters
    ----------
    structured   : the full dict returned by fairify()
    output_path  : if provided, write the README to this file path

    Returns
    -------
    str — the full README content as a plain text string
    """
    ext          = structured.get("extended", {})
    conceptual   = structured.get("conceptual_metadata", {})
    validation   = structured.get("validation", {})
    missing      = structured.get("missing_fields", [])
    dataset_path = structured.get("dataset_path", "")
    generated_at = structured.get("generated_at", datetime.utcnow().isoformat() + "Z")

    sections = [
        _build_title(ext, generated_at),
        _build_general(ext, dataset_path, generated_at),
        _build_access(ext, generated_at),
        _build_file_overview(dataset_path),
        _build_acquisition(ext, conceptual),
        _build_reconstruction(conceptual),
        _build_dictionary(),
        _build_fair(validation, missing),
    ]

    readme = "\n".join(sections)

    if output_path:
        Path(output_path).write_text(readme, encoding="utf-8")
        print(f"README written to: {output_path}")

    return readme
